/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module full_adder(a, b, cin, sum, cout);
  wire _0_;
  wire _1_;
  wire _2_;
  input a;
  input b;
  input cin;
  output cout;
  output sum;
  assign _0_ = ~b;
  assign _1_ = ~(a ^ cin);
  assign sum = _1_ ^ _0_;
  assign _2_ = ~(a & cin);
  assign cout = ~((_1_ | _0_) & _2_);
endmodule
